### ISSUE TITLE
Debug enabled results in hundreds of 'undefined index' errors in main.log

### ISSUE THREAD

**Issue by optpf** [PHPfox-Official/phpfox-v4-issues#2162]
Hi.
If you enable debug mode, the main.log will be filled of hundreds of notices of undefined indexes. The causes are different. These are `notices`, not `errors`.
Here some examples:

```
notice
2018-01-13 18:45:24
[8] Undefined index: content (/var/www/[redacted]/PF.Base/module/user/include/service/callback.class.php) [1217]
Error Code: 33d6f9
Stack trace:
#0 /var/www/[redacted]/PF.Base/module/user/include/service/callback.class.php(1184): User_Service_Callback->_notifyUser('1', '1', '2', '1', 'Hello World!', Array)
#1 /var/www/[redacted]/PF.Base/include/library/phpfox/module/module.class.php(1547): User_Service_Callback->addCommentStatus(Array, 1, 'Admin')
#2 /var/www/[redacted]/PF.Base/include/library/phpfox/phpfox/phpfox.class.php(633): Phpfox_Module->callback('user_status.addComment', Array)
#3 /var/www/[redacted]/PF.Base/module/comment/include/service/process.class.php(221): Phpfox::callback('user_status.addComment', Array, 1, 'Admin')
#4 /var/www/[redacted]/PF.Base/module/comment/include/component/ajax/ajax.class.php(108): Comment_Service_Process->add(Array)
#5 /var/www/[redacted]/PF.Base/include/library/phpfox/ajax/ajax.class.php(213): Comment_Component_Ajax_Ajax->add()
#6 /var/www/[redacted]/PF.Base/include/library/phpfox/phpfox/phpfox.class.php(1472): Phpfox_Ajax->process()
#7 /var/www/[redacted]/PF.Base/start.php(645): Phpfox::run()
#8 /var/www/[redacted]/index.php(9): require('/var/www/[redacted]/PF.Base/sta...')
#9 {main}
```

```
notice
2018-01-14 22:09:26
[8] Undefined index: sSectionTitle (/var/www/[redacted]/PF.Base/file/cache/template/admincp_template_default_block_template-breadcrumbmenu.html.php_admincp.php) [6]
Error Code: f66d33
Stack trace:
#0 /var/www/[redacted]/PF.Base/include/library/phpfox/template/template.class.php(3609): require('/var/www/[redacted]/PF.Base/fil...')
#1 /var/www/[redacted]/PF.Base/include/library/phpfox/template/template.class.php(3595): Phpfox_Template->_requireFile('/var/www/[redacted]/PF.Base/mod...')
#2 /var/www/[redacted]/PF.Base/include/library/phpfox/template/template.class.php(2889): Phpfox_Template->_getFromCache('/var/www/[redacted]/PF.Base/mod...', 'admincp.block.template-breadcrum...')
#3 /var/www/[redacted]/PF.Base/include/library/phpfox/module/module.class.php(1261): Phpfox_Template->getTemplate('admincp.block.template-breadcrum...')
#4 /var/www/[redacted]/PF.Base/include/library/phpfox/phpfox/phpfox.class.php(619): Phpfox_Module->getComponent('admincp.template-breadcrumbmenu', Array, 'block', )
#5 /var/www/[redacted]/PF.Base/include/library/phpfox/phpfox/phpfox.class.php(1796): Phpfox::getBlock('admincp.template-breadcrumbmenu')
#6 /var/www/[redacted]/PF.Base/start.php(645): Phpfox::run()
#7 /var/www/[redacted]/index.php(9): require('/var/www/[redacted]/PF.Base/sta...')
#8 {main}
```

```
notice
2018-01-23 21:58:37
[8] Undefined index: default_value (/var/www/[redacted]/public_html/PF.Base/file/cache/template/flavors_[redacted]_html_search.html.php.php) [21]
Error Code: 7db08a
Stack trace:
#0 /var/www/[redacted]/public_html/PF.Base/include/library/phpfox/template/template.class.php(3609): require('/var/www/[redacted]/public_html...')
#1 /var/www/[redacted]/public_html/PF.Base/include/library/phpfox/template/template.class.php(3595): Phpfox_Template->_requireFile('/var/www/[redacted]/public_html...')
#2 /var/www/[redacted]/public_html/PF.Base/include/library/phpfox/template/template.class.php(2616): Phpfox_Template->_getFromCache('/var/www/[redacted]/public_html...')
#3 /var/www/[redacted]/public_html/PF.Src/Core/View/Functions.php(158): Phpfox_Template->getLayout('search')
#4 /var/www/[redacted]/public_html/PF.Base/file/cache/twig/[redacted]/e/7/e7b00209e0f072633f2f20f386252793b48aaff80a234794915b8b1d22eb48a6.php(191): Core\View\Functions->__toString()
#5 /var/www/[redacted]/public_html/PF.Base/vendor/twig/twig/lib/Twig/Template.php(322): __TwigTemplate_e7b00209e0f072633f2f20f386252793b48aaff80a234794915b8b1d22eb48a6->doDisplay(Array, Array)
#6 /var/www/[redacted]/public_html/PF.Base/vendor/twig/twig/lib/Twig/Template.php(296): Twig_Template->displayWithErrorHandling(Array, Array)
#7 /var/www/[redacted]/public_html/PF.Base/vendor/twig/twig/lib/Twig/Template.php(307): Twig_Template->display(Array)
#8 /var/www/[redacted]/public_html/PF.Src/Core/View/Environment.php(14): Twig_Template->render(Array)
#9 /var/www/[redacted]/public_html/PF.Src/Core/View.php(301): Core\View\Environment->render('@Theme/layout.html', Array)
#10 /var/www/[redacted]/public_html/PF.Base/include/library/phpfox/phpfox/phpfox.class.php(1948): Core\View->getContent()
#11 /var/www/[redacted]/public_html/PF.Base/start.php(645): Phpfox::run()
#12 /var/www/[redacted]/public_html/index.php(9): require('/var/www/[redacted]/public_html...')
#13 {main}
```

```
notice
2018-01-23 21:58:37
[8] Undefined index: default_value (/var/www/[redacted]/public_html/PF.Base/file/cache/template/flavors_[redacted]_html_search.html.php.php) [21]
Error Code: 7db08a
Stack trace:
#0 /var/www/[redacted]/public_html/PF.Base/include/library/phpfox/template/template.class.php(3609): require('/var/www/[redacted]/public_html...')
#1 /var/www/[redacted]/public_html/PF.Base/include/library/phpfox/template/template.class.php(3595): Phpfox_Template->_requireFile('/var/www/[redacted]/public_html...')
#2 /var/www/[redacted]/public_html/PF.Base/include/library/phpfox/template/template.class.php(2616): Phpfox_Template->_getFromCache('/var/www/[redacted]/public_html...')
#3 /var/www/[redacted]/public_html/PF.Src/Core/View/Functions.php(158): Phpfox_Template->getLayout('search')
#4 /var/www/[redacted]/public_html/PF.Base/file/cache/twig/[redacted]/e/7/e7b00209e0f072633f2f20f386252793b48aaff80a234794915b8b1d22eb48a6.php(191): Core\View\Functions->__toString()
#5 /var/www/[redacted]/public_html/PF.Base/vendor/twig/twig/lib/Twig/Template.php(322): __TwigTemplate_e7b00209e0f072633f2f20f386252793b48aaff80a234794915b8b1d22eb48a6->doDisplay(Array, Array)
#6 /var/www/[redacted]/public_html/PF.Base/vendor/twig/twig/lib/Twig/Template.php(296): Twig_Template->displayWithErrorHandling(Array, Array)
#7 /var/www/[redacted]/public_html/PF.Base/vendor/twig/twig/lib/Twig/Template.php(307): Twig_Template->display(Array)
#8 /var/www/[redacted]/public_html/PF.Src/Core/View/Environment.php(14): Twig_Template->render(Array)
#9 /var/www/[redacted]/public_html/PF.Src/Core/View.php(301): Core\View\Environment->render('@Theme/layout.html', Array)
#10 /var/www/[redacted]/public_html/PF.Base/include/library/phpfox/phpfox/phpfox.class.php(1948): Core\View->getContent()
#11 /var/www/[redacted]/public_html/PF.Base/start.php(645): Phpfox::run()
#12 /var/www/[redacted]/public_html/index.php(9): require('/var/www/[redacted]/public_html...')
#13 {main}
```

This happens on a new theme, not modified, that has been inherit from Material Template.
Not tested if happening having the native Material Template active.

Noticed that if you have Nginx as web server instead of Apache, these notices multiplies by 4 at least.
With Apache these notices are less.

### Server informations
Tested with both Nginx and Apache, with Nginx having more notices in respect to Apache
Ubuntu 16.04 LTS 64bit

### phpFox informations
Tested with a fresh install of *4.6* and an upgraded instance from *4.5* to *4.6*. Seems that in the upgraded instance these errors are more.

I add that permissions for users and chmod are set correctly in the cache path.

They happen randomly as is enough to visit 5-6 pages with debug enabled to let errors show. It's enough to go in Quizzes, in an user profile and so on. The log is really, really long. The example posted are just some of the notices.

I don't know if it is something in our end, but if you could check if it is a bug in phpFox that'd be great. This problem makes debugging and developing pretty hard sometimes.

Thank you!

**Comment by neil96** [comment]
Hi @optpf ,

When you enable debug mode, we log anything. These notices are normal and they are not affect to your site.

Regards.

**Comment by optpf** [comment]
Hi Neil, thanks for answering.
I know, but actually it is a bad coding practice... it is better to use `isset()` to check if a variable is available, instead of directly using it in the code - that's why we get so undefined indexes.
Actually, this makes debugging for **real** problems pretty hard because the file can get really huge.
I know they not affect the website, my concern is just for when we develop on phpFox.

Thank you!

Best regards
