### ISSUE TITLE
Photo API's GET method no longer works in 4.6.0

### ISSUE THREAD

**Issue by kirkkhua** [PHPfox-Official/phpfox-v4-issues#2214]
## What happened?
Since version 4.6.0 2 new conditions were added in Photo API (get method) in `/PF.Site/Apps/core-photos/Service/Api.php`, lines 257-262. This lines are blocking requests to Photo API – API returns empty responses:
![photo-api-issue](https://user-images.githubusercontent.com/5412712/38024443-b3c3b704-328d-11e8-842e-22ab470de6f2.jpg)

which is not according to Photo API documentation: https://docs.phpfox.com/display/FOX4DEVDOC/Photo+API

## Steps to reproduce:
1. Make a request with correct token to Photo API according to https://docs.phpfox.com/display/FOX4DEVDOC/Photo+API

## What is expected?
It's expected to receive responses similar to how they're presented in documentation – not an empty array.

## Browsers and Devices tested
-

## Server information
-

...

## phpFox version
phpFox 4.6.0

**Comment by hexplor** [comment]
I can confirm that something is wrong with Photo component. Can't access it either. I'm receiving  500 error instead:

```
error
2018-04-05 07:55:39
[256] Query Error:You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '(photo.type_id = 0 OR (photo.type_id = 1 AND photo.group_id != 0))

)) AS photo
' at line 5 [SELECT pa.name AS album_name, pa.profile_id AS album_profile_id, pa.cover_id AS album_cover_id, pa.timeline_id AS album_timeline_id, ppc.name as category_name, ppc.category_id, l.like_id as is_liked,  u.user_id, u.profile_page_id, u.server_id AS user_server_id, u.user_name, u.full_name, u.gender, u.user_image, u.is_invisible, u.user_group_id, u.language_id, u.birthday, u.country_iso, photo.*
FROM(
(SELECT photo.*
FROM phpfox_photo AS photo
WHERE photo.view_id = 0 AND photo.group_id = 0 AND photo.type_id = 0 AND photo.privacy IN(0,1,2,3,4) AND photo.is_profile_photo IN (0) AND photo.is_cover_photo IN (0) (photo.type_id = 0 OR (photo.type_id = 1 AND photo.group_id != 0))

)) AS photo
LEFT JOIN phpfox_photo_album AS pa
	ON(pa.album_id = photo.album_id)
LEFT JOIN phpfox_photo_category_data AS ppcd
	ON(ppcd.photo_id = photo.photo_id)
LEFT JOIN phpfox_photo_category AS ppc
	ON(ppc.category_id = ppcd.category_id)
LEFT JOIN phpfox_like AS l
	ON(l.type_id = 'photo' AND l.item_id = photo.photo_id AND l.user_id = 1)
JOIN phpfox_user AS u
	ON(u.user_id = photo.user_id)

GROUP BY photo.photo_id
ORDER BY photo.photo_id DESC
LIMIT 10

] (/Volumes/Dane/Witryny/server/eample/sample-social/PF.Base/include/library/phpfox/error/error.class.php) [99]
Error Code: 501a32
Stack trace:
#0 /Volumes/Dane/Witryny/server/eample/sample-social/PF.Base/include/library/phpfox/error/error.class.php(99): trigger_error('Query Error:You have an error in...', 256)
#1 /Volumes/Dane/Witryny/server/eample/sample-social/PF.Base/include/library/phpfox/database/driver/mysql.class.php(176): Phpfox_Error::trigger('Query Error:You have an error in...', 256)
#2 /Volumes/Dane/Witryny/server/eample/sample-social/PF.Base/include/library/phpfox/database/driver/mysql.class.php(660): Phpfox_Database_Driver_Mysql->query('SELECT pa.name AS album_name, pa...', mysqli)
#3 /Volumes/Dane/Witryny/server/eample/sample-social/PF.Base/include/library/phpfox/database/driver/mysql.class.php(833): Phpfox_Database_Driver_Mysql->_getRows('SELECT pa.name AS album_name, pa...', 1, mysqli)
#4 /Volumes/Dane/Witryny/server/eample/sample-social/PF.Base/include/library/phpfox/database/driver/mysql.class.php(1396): Phpfox_Database_Driver_Mysql->getSlaveRows('SELECT pa.name AS album_name, pa...')
#5 /Volumes/Dane/Witryny/server/eample/sample-social/PF.Base/include/library/phpfox/search/browse.class.php(204): Phpfox_Database_Driver_Mysql->execute('getslaverows')
#6 /Volumes/Dane/Witryny/server/eample/sample-social/PF.Site/Apps/core-photos/Service/Api.php(264): Phpfox_Search_Browse->execute()
#7 /Volumes/Dane/Witryny/server/eample/sample-social/PF.Src/Core/Api/ApiServiceBase.php(204): Apps\Core_Photos\Service\Api->gets(Array)
#8 /Volumes/Dane/Witryny/server/eample/sample-social/PF.Src/Core/Route/Controller.php(352): Core\Api\ApiServiceBase->process(Core\Route\RouteUrl, Apps\phpFox_RESTful_API\Service\RestApiTransport, 'gets')
#9 /Volumes/Dane/Witryny/server/eample/sample-social/PF.Base/include/library/phpfox/module/module.class.php(387): Core\Route\Controller->get()
#10 /Volumes/Dane/Witryny/server/eample/sample-social/PF.Base/include/library/phpfox/phpfox/phpfox.class.php(1540): Phpfox_Module->setController()
#11 /Volumes/Dane/Witryny/server/eample/sample-social/PF.Base/start.php(645): Phpfox::run()
#12 /Volumes/Dane/Witryny/server/eample/sample-social/index.php(9): require('/Volumes/Dane/Witryny/server/dev...')
#13 {main}
```

**Comment by hexplor** [comment]
This is still bug in 4.6.1.  http://example.com/restful_api/photo returns 0 results.

**Comment by neil96** [comment]
Restful Api is a separate app, we do not have new build for this app now.

Regards

**Comment by hexplor** [comment]
Yeah, but it's related to core-photo app :), more specifically this file:  /PF.Site/Apps/core-photos/Service/Api.php and this line
```
        if (!Phpfox::getParam('photo.display_timeline_photo_within_gallery')) {
            $this->search()->setCondition('(photo.type_id = 0 OR (photo.type_id = 1 AND photo.group_id != 0))');
        }
```

**Comment by david-phpFox** [comment]
Will support in Mobile Api App
