### ISSUE TITLE
Clicking on upgrade for quiz from admincp throws 500 error phpfox v4.71

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2462]
`Error code: bb7801

[256] Query Error:Duplicate entry '0' for key 'PRIMARY' [ALTER TABLE phpfox_quiz_result ADD PRIMARY KEY (`result_id`)] (/home/xxxx/public_html/PF.Base/include/library/phpfox/error/error.class.php) [99] Error Code: bb7801 Stack trace: #0 /home/xxxx/public_html/PF.Base/include/library/phpfox/error/error.class.php(99): trigger_error('Query Error:Duplicate entry '0' ...', 256) #1 /home/xxxx/public_html/PF.Base/include/library/phpfox/database/driver/mysql.class.php(182): Phpfox_Error::trigger('Query Error:Duplicate entry '0' ...', 256) #2 /home/xxxx/public_html/PF.Base/include/library/phpfox/database/driver/mysql.class.php(2148): Phpfox_Database_Driver_Mysql->query('ALTER TABLE phpfox_quiz_result A...') #3 /home/xxxx/public_html/PF.Src/Core/App/Install/Database/Table.php(275): Phpfox_Database_Driver_Mysql->updatePrimaryKeys('phpfox_quiz_result', Array, 'result_id') #4 /home/xxxx/public_html/PF.Src/Core/App/Install/Database/Table.php(213): Core\App\Install\Database\Table->_updatePrimaryKeys() #5 /home/xxxx/public_html/PF.Src/Core/App/App.php(530): Core\App\Install\Database\Table->install() #6 /home/xxxx/public_html/PF.Src/Core/Installation/Manager.php(1470): Core\App\App->processInstall() #7 /home/xxxx/public_html/PF.Src/Core/Installation/Manager.php(544): Core\Installation\Manager->callRunInstallForApp('Core_Quizzes', 'core-quizzes', ) #8 /home/xxxx/public_html/PF.Src/Core/Installation/Manager.php(965): Core\Installation\Manager->runInstallForApp(Array) #9 /home/xxxx/public_html/PF.Src/Core/Installation/Manager.php(226): Core\Installation\Manager->runInstall(Array) #10 /home/xxxx/public_html/PF.Src/Core/Installation/Manager.php(201): Core\Installation\Manager->onInstall(Array) #11 /home/xxxx/public_html/PF.Base/module/admincp/include/component/controller/store/ftp.class.php(17): Core\Installation\Manager->install(Array, ) #12 /home/xxxx/public_html/PF.Base/include/library/phpfox/module/module.class.php(1180): Admincp_Component_Controller_Store_Ftp->process() #13 /home/xxxx/public_html/PF.Base/include/library/phpfox/module/module.class.php(589): Phpfox_Module->getComponent('admincp.store.ftp', Array, 'controller') #14 /home/xxxx/public_html/PF.Base/include/library/phpfox/module/module.class.php(383): Phpfox_Module->getController() #15 /home/xxxx/public_html/PF.Base/module/admincp/include/component/controller/index.class.php(383): Phpfox_Module->setController('admincp.store.ftp') #16 /home/xxxx/public_html/PF.Base/include/library/phpfox/module/module.class.php(1180): Admincp_Component_Controller_Index->process() #17 /home/xxxx/public_html/PF.Base/include/library/phpfox/module/module.class.php(589): Phpfox_Module->getComponent('admincp.index', Array, 'controller') #18 /home/xxxx/public_html/PF.Base/include/library/phpfox/phpfox/phpfox.class.php(1655): Phpfox_Module->getController() #19 /home/xxxx/public_html/PF.Base/start.php(631): Phpfox::run() #20 /home/xxxx/public_html/index.php(9): require('/home/xxxx/public_html/PF...') #21 {main}`

**Comment by harrison05** [comment]
It seems an issue from your database, it lost **auto_increment** property for column **result_id**. We don't meet this issue in our sites, because in the install code, we added **auto_increment** for this column. Does it work on your site now?

**Comment by prepperz** [comment]
I had the debug on... when I installed the app. That is why.

**Comment by david-phpFox** [comment]
Please add auto_increment property for column result_id when have issue. We can not reproduce it. Please check it again on Quizzes 4.7.0.
